### ISSUE TITLE
Trouble setting up Pulumi + GitHub Actions + Azure

### ISSUE THREAD

**Issue by jacobATcertifiedfoodDotinfo** [pulumi/pulumi-hugo#2283]
### What happened?

This is not a Pulumi bug report.
This is a report about documentation that can be improved.

I would like to share details about how this trouble can be avoided.
I wrote a .sh script to setup the Azure creds.

### Steps to reproduce

See:
https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/

See:
https://pulumi-community.slack.com/archives/C01PF3E1B8V/p1669593776987969

### Expected Behavior

Pulumi deploys the stack to Azure on the Git commit GitHub Action.

### Actual Behavior

Error: "Insufficient privileges to complete the operation."

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hi @jacobATcertifiedfoodDotinfo Would you mind being a little more specific about what you do and what you expected to happen? How specifically can the documentation be improved?

Looking at the post in Community Slack, it appears you tried to provide Pulumi with access to Azure by logging in from the Azure CLI, but without passing credentials directly to the GitHub Action. Is that correct?

**Comment by jacobATcertifiedfoodDotinfo** [comment]
@RobbieMcKinstry the example `yaml` files on https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/ are for AWS.

Are there also example `yaml` files for Azure?

Here is what I used:
Note: there are only 3 `uses` here (there are 4 `uses` in the AWS example)
```
name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pulumi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - run: go mod download
      - uses: pulumi/actions@v3
        with:
          work-dir: ./pulumi
          command: up
          stack-name: org-name/stack-name # When using an individual account, only use stack-name.
          refresh: true
          upsert: true
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

```

To get the Azure creds, I wrote this:
```
set -e

if [[ $# != 1 ]]; then
  echo "exactly one argument expected: env prefix (e.g. alfa, bravo, etc.)"
  exit
fi

# Get ID for subscription with matching env prefix
subscriptionId=$(az account list --query "[?starts_with(name, '$1')]" | jq -r '.[] | .id')

# Create AAD app
displayName=$1'-pulumi-aad-app'

existingApps=$(az ad app list --query "[?displayName == '"$displayName"']" | jq '.[]')

if [[ ! -z "$existingApps" ]]; then
  echo "AAD app with name '$displayName' already exists (AAD allows duplicate AAD app names, but I'm guessing you did not intend to use a duplicate name)"
  exit
fi

appId=$(az rest --method post --uri https://graph.microsoft.com/v1.0/applications --body '{"displayName": "'$displayName'"}' | jq -r '.appId')

# Create AAD service principal
servicePrincipalId=$(az rest --method post --uri https://graph.microsoft.com/v1.0/servicePrincipals --body '{"appId": "'$appId'"}' | jq -r '.id')

# Create AAD service principal password
servicePrincipalPassword=$(az rest --method post --uri https://graph.microsoft.com/v1.0/servicePrincipals/$servicePrincipalId/addPassword  | jq -r '.secretText')

# Assign subscription "Owner" role to service principal
response=$(az role assignment create --assignee "$servicePrincipalId" --role "Owner" --subscription "$subscriptionId")

# Grant Azure Active Directory Graph Directory.ReadWrite.All API permission to service principal
#
# az rest --method get --uri https://graph.microsoft.com/v1.0/servicePrincipals/60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d
#
# Azure Active Directory Graph object:
# {
#   "id": "60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d",
#   "appId": "00000002-0000-0000-c000-000000000000",
#   "appDisplayName": "Windows Azure Active Directory"
# }
#
# Directory.ReadWrite.All permission ID: 78c8a3c8-a07e-4b9e-af1b-b5ccab50a175
response=$(az rest --subscription $subscriptionId --method post --uri https://graph.microsoft.com/v1.0/servicePrincipals/60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d/appRoleAssignedTo --body '{ "principalId": "'$servicePrincipalId'", "resourceId": "60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d", "appRoleId": "78c8a3c8-a07e-4b9e-af1b-b5ccab50a175" }')

# Grant Azure Active Directory Graph Application.ReadWrite.All API permission to service principal
#
# az rest --method get --uri https://graph.microsoft.com/v1.0/servicePrincipals/60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d
#
# Azure Active Directory Graph object:
# {
#   "id": "60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d",
#   "appId": "00000002-0000-0000-c000-000000000000",
#   "appDisplayName": "Windows Azure Active Directory"
# }
#
# Application.ReadWrite.All permission ID: 1cda74f2-2616-4834-b122-5cb1b07f8a59
response=$(az rest --subscription $subscriptionId --method post --uri https://graph.microsoft.com/v1.0/servicePrincipals/60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d/appRoleAssignedTo --body '{ "principalId": "'$servicePrincipalId'", "resourceId": "60b3f8d5-92c6-4f51-93f0-8d0f0825cf9d", "appRoleId": "1cda74f2-2616-4834-b122-5cb1b07f8a59" }')

echo 'ARM_TENANT_ID:'
echo $(az account show | jq -r '.tenantId')

echo 'ARM_SUBSCRIPTION_ID:'
echo $subscriptionId

echo 'ARM_CLIENT_ID:'
echo $appId

echo 'ARM_CLIENT_SECRET:'
echo $servicePrincipalPassword
```
