### ISSUE TITLE
Add ESC details to Azure Native installation registry docs

### ISSUE THREAD

**Issue by interurban** [pulumi/pulumi-hugo#3590]
Add details about how ESC and OIDC configuration to our Aws registry page:
https://www.pulumi.com/registry/packages/azure-native/installation-configuration/

**Comment by toriancrane** [comment]
From [this thread](https://pulumi.slack.com/archives/C05G9TV06MB/p1697109906050219):

Hey all,

I'm running into what I think was the last issue mentioned in this thread as far as Pulumi hanging on creating a resource group and then failing. I'm getting a `githubAssertion`.

My environment is configured like the following:

```
values:
  azure:
    login:
      fn::open::azure-login:
        clientId: bb....
        tenantId: 70....
        subscriptionId: /subscriptions/....
        oidc: true
  environmentVariables:
    ARM_USE_OIDC: 'true'
    ARM_CLIENT_ID: ${azure.login.clientId}
    ARM_TENANT_ID: ${azure.login.tenantId}
    ARM_OIDC_REQUEST_TOKEN: ${azure.login.oidc.token}
    ARM_SUBSCRIPTION_ID: ${azure.login.subscriptionId}
    ARM_OIDC_REQUEST_URL: https://api.pulumi.com/oidc
```

I also tried running using `ARM_OIDC_TOKEN`  but that failed with the following error:

```
error: OIDC authentication was requested via useOidc/ARM_USE_OIDC but no token and/or
    request URL were configured.
```
