### ISSUE TITLE
Additional examples

### ISSUE THREAD

**Issue by tksrc** [pulumi/pulumi-hugo#430]
File: [themes/default/content/docs/intro/concepts/config.md](https://www.pulumi.com/docs/intro/concepts/config/)

Could we please add an example on how to load configs based on namespaces that are not the same as the project name?

e.g. 

Pulumi.\<stack\>.yaml
```yaml
config:
  management:resource_groups:
    - name: infra
    - name: security
```

Accessing the config using Python (for example)

```python
import pulumi

management_conf = pulumi.Config("management")
resource_groups = management_conf.get_object("resource_groups")
```

For some reason it wasn't clear to me that I needed to pass the namespace to the Config() constructor. I was using `pulumi.Config()` instead.
